#!/bin/bash
# Quick Deployment Script - Run this for deployment checklist

echo "🚀 Kickscale Deployment Checklist"
echo "=================================="
echo ""
echo "✅ Step 1: Code Ready"
echo "   - Run: git push to GitHub"
echo ""
echo "✅ Step 2: Deploy Backend"
echo "   - Go to: https://railway.app"
echo "   - Import GitHub repo"
echo "   - Wait for 'Active' status"
echo "   - Copy Railway URL"
echo ""
echo "✅ Step 3: Deploy Frontend"
echo "   - Go to: https://vercel.com"
echo "   - Add environment variable:"
echo "     VITE_API_BASE_URL = [YOUR_RAILWAY_URL]/api"
echo "   - Deploy"
echo ""
echo "✅ Step 4: Test Live"
echo "   - Open Vercel URL in browser"
echo "   - Test all features"
echo ""
echo "✅ Step 5: Share URLs"
echo "   - Frontend URL: https://[vercel-project].vercel.app"
echo "   - Backend URL: https://[railway-project].up.railway.app/api"
echo ""
echo "🎉 Done! Your app is live!"
